#! /bin/sh

CURDIR=pwd

ORIGIN="user.github.io"
CODENAME="testing"
REPOARCH="all"
POLICY="main"
KEY="Example"
OVERRIDE="override.testing"

. "aptgit.conf"

while [[$# > 1]]; do
	arg="$1"
	case $arg in
		-d|--directory)
			CURDIR="$2"
			shift
		;;
		-o|--origin)
			ORIGIN="$2"
			shift
		;;
		-c|--codename)
			CODENAME="$2"
			shift
		;;
		-a|--arch)
			REPOARCH="$2"
			shift
		;;
		-p|--POLICY)
			POLICY="$2"
			shift
		;;
		-k|--key)
			KEY="$2"
			shift
		;;
		-q|--override)
			OVERRIDE="$2"
			shift
		;;
		-m,|--message)
			MESSAGE="$2"
			shift
		;;
		-c|--check)
			CHECK="YES"
			shift
		;;
		-r|--reset)
			RESET="YES"
			shift
		;;
		-u|--user|--org|--organization)
			ORG="YES"
			shift
		;;
	esac
done

BASEDIR="$CURDIR/debian"
CONFDIR="$CURDIR/debian/conf"
SRCDIR="$CURDIR/../debpackages"

confirm()
	read -r -p "${1: -Are you sure? [y/N]} " response
	case $response in
		[yY][eE][sS])
			return "YES"
			;;
		*)
			return "NO"
			;;
	esac

checkdepends()
	sudo apt-get install gnupg git rng-tools dpkg-sig reprepo
	sudo service rng-tools start

generatekey()
	gpg --gen-key

enterkey()
	KEYED="NO"
	while ["$KEYED"="NO"]; do
		read -r -p "Enter the key that you want to use to sign your repository" KEY
		KEYED=confirm
	done

createdirs()
	if ["$CONFDIR" -d]; then
	else
		mkdir -p "$CONFDIR"
	fi

gendistrofile()
	echo "Origin: $ORIGIN"		> "$CONFDIR/distributions"
	echo "Label: $ORIGIN"		>> "$CONFDIR/distributions"
	echo "Codename: $CODENAME"	>> "$CONFDIR/distributions"
	echo "Architectures: $REPOARCH"	>> "$CONFDIR/distributions"
	echo "Components: $POLICY"	>> "$CONFDIR/distributions"
	echo "Description: $ORIGIN"	>> "$CONFDIR/distributions"
	echo "SignWith: $KEY"		>> "$CONFDIR/distributions"
	echo "DebOverride: $OVERRIDE"	>> "$CONFDIR/distributions"
	echo "DscOverride: $OVERRIDE"	>> "$CONFDIR/distributions"
	touch "$CONFDIR/$OVERRIDE"

genconfoptions()
	echo "verbose"
	echo "ask-passphrase"
	echo "basedir $BASEDIR"

generaterkey()
	gpg --armor --output "$CURDIR/$ORIGIN.gpg.key" --export $KEY

includepackages()
	cd $BASEDIR
	reprepo include "$SRCDIR/*"

if ["$CURDIR/.git" -d]; then
	if ["$RESET" = "YES"]; then
		CHECK="YES"
		rm -rf "$BASEDIR"
	fi
	if ["$CHECK" = "YES"]; then
		checkdepends
	fi
	if ["$RESET" = "YES"]; then
		generatekey
		enterkey
		createdirs
	fi
	gendistrofile
	genconfoptions
	generaterkey
	includepackages
	DATE=date
	if ["$ORG" = "YES"]; then
		git add . && git commit -am "Repository update: $MESSAGE $DATE" && git push origin master
	else
		git add . && git commit -am "Repository update: $MESSAGE $DATE" && git push origin gh-pages
	fi
else
	echo "Fatal Error, this is not a git repository. Please create a git repository and enable github pages to use this script."
fi